### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by AbdulrahmanMasoud** [Fatmakaram97/DSC-tasks#1]
مشاء الله الله ينور علي الشغل الجميل ده 
الكود منظم 
مكتوب كومنتات بتوضح الجزء ده بيعمل ايه بس للاسف انت مش كاتبه علي كل حاجه كومنت كانت هتبقا افضل لو عملتي علي كل حاجه كومنت بيوضح بالتفصيل الجزء ده بيعمل اي 
بس ده ميمنعش ان التاسك عظمه 
ف عاش جدا

**Comment by Fatmakaram97** [comment]
شكرا جدا 😃

**Comment by AbdulrahmanMasoud** [comment]
updated

**Comment by Fatmakaram97** [comment]
Many thanks
